version: 2.1
jobs:
  hi_job:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: letsRunCI
          command: |
              echo "hi salah"

workflows:
  new_wokflow:
    jobs:
      - hi_job