version: 2.1

jobs:
  ansible1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - run  :
            name: Ansible Inventory
            command : |
                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory
      - persist_to_workspace:
            root: ~/
            path: inventory
          

  ansible2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - at_workspace:
            at: ~
      - run : cat ~/inventory        


workflows:
  CI_NODEJS:
    jobs:
      - ansible1
      - ansible2:
          requires : [ansible1]
