# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y

jobs:
  inventory:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - run  :
            name: Get Instance IP - Ansible Inventory
            command : |
                echo "[all]" > ~/inventory
                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/inventory
      - persist_to_workspace:
            root: ~/
            paths: 
             - inventory
          

  ansible:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - install_ansible
      - attach_workspace:
            at: ~/      
      - run : 
          name: ansible_playbook
          command: |
            cat ~/inventory 
            ansible --version #Ansible installtion checkpoint
            ansible-playbook -i inventory main-remote.yml 



workflows:
  Ansible_workflow:
    jobs:
      - inventory
      - ansible:
          requires : [inventory]
    
