version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: "ASIAXCOKHKKSGQR5AOF2"
          aws-secret-access-key: "kj03dmAj+IX8USNRXmgeKs/6SZgYlsP4aHe8hdY/"
          aws-region: "us-east-1"
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
