version: '2.1'

jobs:
  aws-cli-cred-setup:
    docker:
      image: circleci/aws-cli@2.0
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup
